### ISSUE TITLE
Raise and focus firefox when a new window is added as tab

### ISSUE THREAD

**Issue by puchu** [Emano-Waldeck/Single-Window#1]
Hi,

thanks for this nice addon.

One feature i'm missing is the "raise and focus" of the main window when "Single Window Mode" is enabled

With Single Window Mode enabled, it get with "firefox --search foo" a new tab added but firefox stays in background

with Single Window Mode disabled, it get with "firefox --search foo" a new window that takes focus and is raised

Would be nice to get this implemented

Have a nice day

**Comment by Emano-Waldeck** [comment]
Thanks for the report. It is fixed on 0.1.3 release.
