### ISSUE TITLE
Firefox 63.0 search doesn't open in a new tab

### ISSUE THREAD

**Issue by RedirectCleaner** [Emano-Waldeck/Single-Window#3]
After the update to Firefox 63.0 the addon stopped working when a search is opened from the cmd-line or "Open Link in New Window" is selected.

Before FF 63.0 with "Single Window Mode enabled" the cmd

`firefox --search foo`

led to a new tab which used the default search engine to search for "foo".
After the update to FF 63.0 the same cmd leads to an empty new tab instead.
The same happens when selecting the "Open Link in New Window" entry in the context menu

**Comment by Emano-Waldeck** [comment]
I've released a new version. please give it a try. I havent tried the extension on Windows though. If you still have the issue, let me know.

**Comment by RedirectCleaner** [comment]
thanks, the latest release fixes the bug
